name: Sync NNUE

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout our repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Add NNUE remote
        run: |
          git remote remove nnue || true
          git remote add nnue https://${{ secrets.PAT_TOKEN }}@github.com/MaggiCoder16/NNUE_Final.git
          git fetch nnue main

      - name: Merge changes into our repo
        run: |
          git merge nnue/main --allow-unrelated-histories -X ours --no-edit || true
          git merge nnue/main -X ours --no-edit || true
          git checkout --ours .
          git add -A
          git commit -m "Sync NNUE updates (ours wins on conflicts)" || echo "No changes to commit"

      - name: Push changes
        run: git push origin main
